name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://elaine-ch.github.io/Lab6_Part1_Starter/
          # budgetPath: ./budget.json test performance budgets
          uploadArtifacts: true # save results as an action artifacts
